server:
  port: 8080

app:
  topics:
    orders: orders.v1
    dlt: orders.v1.dlt

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orders
    username: app
    password: app
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.jdbc.time_zone: UTC

  kafka:
    bootstrap-servers: localhost:9094   # make sure it's lowercase "localhost"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true
        acks: all
    consumer:
      group-id: reliable-orders
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        isolation.level: read_committed

management:
  endpoints.web.exposure.include: health,info,metrics
